name: dart_ollama
description: A Dart package for interacting with Ollama and ChatGPT APIs. Supports streaming chat responses, tool/function calling, image support, and both Ollama and ChatGPT backends.
version: 0.1.0
homepage: https://github.com/brynjen/dart-ollama
repository: https://github.com/brynjen/dart-ollama
issue_tracker: https://github.com/brynjen/dart-ollama/issues

environment:
  sdk: ^3.8.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
