/// Represents a text embedding generated by an LLM.
class LLMEmbedding {
  LLMEmbedding({
    required this.model,
    required this.embedding,
    required this.promptEvalCount,
  });

  /// The model that generated this embedding.
  final String model;

  /// The embedding vector.
  final List<double> embedding;

  /// Number of tokens in the input text.
  final int promptEvalCount;

  /// Creates an embedding from a JSON map.
  factory LLMEmbedding.fromJson(Map<String, dynamic> json) => LLMEmbedding(
        model: json['model'],
        embedding: json['embeddings'] as List<double>,
        promptEvalCount: json['prompt_eval_count'],
      );
}

