// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This file was generated by ffigen from llama.h
// To regenerate: dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for llama.cpp
class LlamaBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LlamaBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LlamaBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initialize the llama backend
  void llama_backend_init() {
    return _llama_backend_init();
  }

  late final _llama_backend_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('llama_backend_init');
  late final _llama_backend_init = _llama_backend_initPtr
      .asFunction<void Function()>();

  /// Cleanup the llama backend - call once at the end
  void llama_backend_free() {
    return _llama_backend_free();
  }

  late final _llama_backend_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('llama_backend_free');
  late final _llama_backend_free = _llama_backend_freePtr
      .asFunction<void Function()>();

  /// Get default model parameters
  llama_model_params llama_model_default_params() {
    return _llama_model_default_params();
  }

  late final _llama_model_default_paramsPtr =
      _lookup<ffi.NativeFunction<llama_model_params Function()>>(
        'llama_model_default_params',
      );
  late final _llama_model_default_params = _llama_model_default_paramsPtr
      .asFunction<llama_model_params Function()>();

  /// Load a model from file
  ffi.Pointer<llama_model> llama_load_model_from_file(
    ffi.Pointer<ffi.Char> path_model,
    llama_model_params params,
  ) {
    return _llama_load_model_from_file(path_model, params);
  }

  late final _llama_load_model_from_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_model> Function(
            ffi.Pointer<ffi.Char>,
            llama_model_params,
          )
        >
      >('llama_load_model_from_file');
  late final _llama_load_model_from_file = _llama_load_model_from_filePtr
      .asFunction<
        ffi.Pointer<llama_model> Function(
          ffi.Pointer<ffi.Char>,
          llama_model_params,
        )
      >();

  /// Free a model
  void llama_free_model(ffi.Pointer<llama_model> model) {
    return _llama_free_model(model);
  }

  late final _llama_free_modelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_model>)>>(
        'llama_free_model',
      );
  late final _llama_free_model = _llama_free_modelPtr
      .asFunction<void Function(ffi.Pointer<llama_model>)>();

  /// Get default context parameters
  llama_context_params llama_context_default_params() {
    return _llama_context_default_params();
  }

  late final _llama_context_default_paramsPtr =
      _lookup<ffi.NativeFunction<llama_context_params Function()>>(
        'llama_context_default_params',
      );
  late final _llama_context_default_params = _llama_context_default_paramsPtr
      .asFunction<llama_context_params Function()>();

  /// Create a context with a model
  ffi.Pointer<llama_context> llama_new_context_with_model(
    ffi.Pointer<llama_model> model,
    llama_context_params params,
  ) {
    return _llama_new_context_with_model(model, params);
  }

  late final _llama_new_context_with_modelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_context> Function(
            ffi.Pointer<llama_model>,
            llama_context_params,
          )
        >
      >('llama_new_context_with_model');
  late final _llama_new_context_with_model = _llama_new_context_with_modelPtr
      .asFunction<
        ffi.Pointer<llama_context> Function(
          ffi.Pointer<llama_model>,
          llama_context_params,
        )
      >();

  /// Free a context
  void llama_free(ffi.Pointer<llama_context> ctx) {
    return _llama_free(ctx);
  }

  late final _llama_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_context>)>
      >('llama_free');
  late final _llama_free = _llama_freePtr
      .asFunction<void Function(ffi.Pointer<llama_context>)>();

  /// Get vocab size
  int llama_n_vocab(ffi.Pointer<llama_model> model) {
    return _llama_n_vocab(model);
  }

  late final _llama_n_vocabPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<llama_model>)>>(
        'llama_n_vocab',
      );
  late final _llama_n_vocab = _llama_n_vocabPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Get context size
  int llama_n_ctx_train(ffi.Pointer<llama_model> model) {
    return _llama_n_ctx_train(model);
  }

  late final _llama_n_ctx_trainPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<llama_model>)>>(
        'llama_n_ctx_train',
      );
  late final _llama_n_ctx_train = _llama_n_ctx_trainPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Get embedding size
  int llama_n_embd(ffi.Pointer<llama_model> model) {
    return _llama_n_embd(model);
  }

  late final _llama_n_embdPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<llama_model>)>>(
        'llama_n_embd',
      );
  late final _llama_n_embd = _llama_n_embdPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Get vocabulary type
  llama_vocab_type llama_vocab_type$1(ffi.Pointer<llama_model> model) {
    return llama_vocab_type.fromValue(_llama_vocab_type$1(model));
  }

  late final _llama_vocab_type$1Ptr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<llama_model>)>
      >('llama_vocab_type');
  late final _llama_vocab_type$1 = _llama_vocab_type$1Ptr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Get context size
  int llama_n_ctx(ffi.Pointer<llama_context> ctx) {
    return _llama_n_ctx(ctx);
  }

  late final _llama_n_ctxPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<llama_context>)>
      >('llama_n_ctx');
  late final _llama_n_ctx = _llama_n_ctxPtr
      .asFunction<int Function(ffi.Pointer<llama_context>)>();

  /// Get batch size
  int llama_n_batch(ffi.Pointer<llama_context> ctx) {
    return _llama_n_batch(ctx);
  }

  late final _llama_n_batchPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<llama_context>)>
      >('llama_n_batch');
  late final _llama_n_batch = _llama_n_batchPtr
      .asFunction<int Function(ffi.Pointer<llama_context>)>();

  /// Beginning of sentence token
  int llama_token_bos(ffi.Pointer<llama_model> model) {
    return _llama_token_bos(model);
  }

  late final _llama_token_bosPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_bos');
  late final _llama_token_bos = _llama_token_bosPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// End of sentence token
  int llama_token_eos(ffi.Pointer<llama_model> model) {
    return _llama_token_eos(model);
  }

  late final _llama_token_eosPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_eos');
  late final _llama_token_eos = _llama_token_eosPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Classification/separation token
  int llama_token_cls(ffi.Pointer<llama_model> model) {
    return _llama_token_cls(model);
  }

  late final _llama_token_clsPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_cls');
  late final _llama_token_cls = _llama_token_clsPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Sentence separator token
  int llama_token_sep(ffi.Pointer<llama_model> model) {
    return _llama_token_sep(model);
  }

  late final _llama_token_sepPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_sep');
  late final _llama_token_sep = _llama_token_sepPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Newline token
  int llama_token_nl(ffi.Pointer<llama_model> model) {
    return _llama_token_nl(model);
  }

  late final _llama_token_nlPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_nl');
  late final _llama_token_nl = _llama_token_nlPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Padding token
  int llama_token_pad(ffi.Pointer<llama_model> model) {
    return _llama_token_pad(model);
  }

  late final _llama_token_padPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_pad');
  late final _llama_token_pad = _llama_token_padPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Prefix token (for infill)
  int llama_token_prefix(ffi.Pointer<llama_model> model) {
    return _llama_token_prefix(model);
  }

  late final _llama_token_prefixPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_prefix');
  late final _llama_token_prefix = _llama_token_prefixPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Middle token (for infill)
  int llama_token_middle(ffi.Pointer<llama_model> model) {
    return _llama_token_middle(model);
  }

  late final _llama_token_middlePtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_middle');
  late final _llama_token_middle = _llama_token_middlePtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Suffix token (for infill)
  int llama_token_suffix(ffi.Pointer<llama_model> model) {
    return _llama_token_suffix(model);
  }

  late final _llama_token_suffixPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_suffix');
  late final _llama_token_suffix = _llama_token_suffixPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// End of text token (for infill)
  int llama_token_eot(ffi.Pointer<llama_model> model) {
    return _llama_token_eot(model);
  }

  late final _llama_token_eotPtr =
      _lookup<
        ffi.NativeFunction<llama_token Function(ffi.Pointer<llama_model>)>
      >('llama_token_eot');
  late final _llama_token_eot = _llama_token_eotPtr
      .asFunction<int Function(ffi.Pointer<llama_model>)>();

  /// Check if token is EOG (end of generation)
  bool llama_token_is_eog(ffi.Pointer<llama_model> model, int token) {
    return _llama_token_is_eog(model, token);
  }

  late final _llama_token_is_eogPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<llama_model>, llama_token)
        >
      >('llama_token_is_eog');
  late final _llama_token_is_eog = _llama_token_is_eogPtr
      .asFunction<bool Function(ffi.Pointer<llama_model>, int)>();

  /// Check if token is control
  bool llama_token_is_control(ffi.Pointer<llama_model> model, int token) {
    return _llama_token_is_control(model, token);
  }

  late final _llama_token_is_controlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<llama_model>, llama_token)
        >
      >('llama_token_is_control');
  late final _llama_token_is_control = _llama_token_is_controlPtr
      .asFunction<bool Function(ffi.Pointer<llama_model>, int)>();

  /// Convert text to tokens
  /// Returns the number of tokens, negative on error
  int llama_tokenize(
    ffi.Pointer<llama_model> model,
    ffi.Pointer<ffi.Char> text,
    int text_len,
    ffi.Pointer<llama_token> tokens,
    int n_tokens_max,
    bool add_special,
    bool parse_special,
  ) {
    return _llama_tokenize(
      model,
      text,
      text_len,
      tokens,
      n_tokens_max,
      add_special,
      parse_special,
    );
  }

  late final _llama_tokenizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<llama_model>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Pointer<llama_token>,
            ffi.Int32,
            ffi.Bool,
            ffi.Bool,
          )
        >
      >('llama_tokenize');
  late final _llama_tokenize = _llama_tokenizePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_model>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<llama_token>,
          int,
          bool,
          bool,
        )
      >();

  /// Convert token to text piece
  /// Returns the number of characters, negative on error
  int llama_token_to_piece(
    ffi.Pointer<llama_model> model,
    int token,
    ffi.Pointer<ffi.Char> buf,
    int length,
    int lstrip,
    bool special,
  ) {
    return _llama_token_to_piece(model, token, buf, length, lstrip, special);
  }

  late final _llama_token_to_piecePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<llama_model>,
            llama_token,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int32,
            ffi.Bool,
          )
        >
      >('llama_token_to_piece');
  late final _llama_token_to_piece = _llama_token_to_piecePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_model>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          bool,
        )
      >();

  /// Detokenize - convert tokens back to text
  int llama_detokenize(
    ffi.Pointer<llama_model> model,
    ffi.Pointer<llama_token> tokens,
    int n_tokens,
    ffi.Pointer<ffi.Char> text,
    int text_len_max,
    bool remove_special,
    bool unparse_special,
  ) {
    return _llama_detokenize(
      model,
      tokens,
      n_tokens,
      text,
      text_len_max,
      remove_special,
      unparse_special,
    );
  }

  late final _llama_detokenizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<llama_model>,
            ffi.Pointer<llama_token>,
            ffi.Int32,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Bool,
            ffi.Bool,
          )
        >
      >('llama_detokenize');
  late final _llama_detokenize = _llama_detokenizePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_model>,
          ffi.Pointer<llama_token>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          bool,
          bool,
        )
      >();

  /// Initialize a batch (deprecated, use llama_batch_get_one or manual allocation)
  llama_batch llama_batch_init(int n_tokens, int embd, int n_seq_max) {
    return _llama_batch_init(n_tokens, embd, n_seq_max);
  }

  late final _llama_batch_initPtr =
      _lookup<
        ffi.NativeFunction<
          llama_batch Function(ffi.Int32, ffi.Int32, ffi.Int32)
        >
      >('llama_batch_init');
  late final _llama_batch_init = _llama_batch_initPtr
      .asFunction<llama_batch Function(int, int, int)>();

  /// Free batch memory
  void llama_batch_free(llama_batch batch) {
    return _llama_batch_free(batch);
  }

  late final _llama_batch_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(llama_batch)>>(
        'llama_batch_free',
      );
  late final _llama_batch_free = _llama_batch_freePtr
      .asFunction<void Function(llama_batch)>();

  /// Get a batch for a single sequence of tokens
  llama_batch llama_batch_get_one(
    ffi.Pointer<llama_token> tokens,
    int n_tokens,
    int pos_0,
    int seq_id,
  ) {
    return _llama_batch_get_one(tokens, n_tokens, pos_0, seq_id);
  }

  late final _llama_batch_get_onePtr =
      _lookup<
        ffi.NativeFunction<
          llama_batch Function(
            ffi.Pointer<llama_token>,
            ffi.Int32,
            llama_pos,
            llama_seq_id,
          )
        >
      >('llama_batch_get_one');
  late final _llama_batch_get_one = _llama_batch_get_onePtr
      .asFunction<
        llama_batch Function(ffi.Pointer<llama_token>, int, int, int)
      >();

  /// Run the model on the batch
  /// Returns 0 on success, 1 if could not find KV slot, < 0 on error
  int llama_decode(ffi.Pointer<llama_context> ctx, llama_batch batch) {
    return _llama_decode(ctx, batch);
  }

  late final _llama_decodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<llama_context>, llama_batch)
        >
      >('llama_decode');
  late final _llama_decode = _llama_decodePtr
      .asFunction<int Function(ffi.Pointer<llama_context>, llama_batch)>();

  /// Get logits for all tokens (requires logits_all = true)
  ffi.Pointer<ffi.Float> llama_get_logits(ffi.Pointer<llama_context> ctx) {
    return _llama_get_logits(ctx);
  }

  late final _llama_get_logitsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>)
        >
      >('llama_get_logits');
  late final _llama_get_logits = _llama_get_logitsPtr
      .asFunction<
        ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>)
      >();

  /// Get logits for the i-th token
  ffi.Pointer<ffi.Float> llama_get_logits_ith(
    ffi.Pointer<llama_context> ctx,
    int i,
  ) {
    return _llama_get_logits_ith(ctx, i);
  }

  late final _llama_get_logits_ithPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, ffi.Int32)
        >
      >('llama_get_logits_ith');
  late final _llama_get_logits_ith = _llama_get_logits_ithPtr
      .asFunction<
        ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, int)
      >();

  /// Clear the KV cache
  void llama_kv_cache_clear(ffi.Pointer<llama_context> ctx) {
    return _llama_kv_cache_clear(ctx);
  }

  late final _llama_kv_cache_clearPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_context>)>
      >('llama_kv_cache_clear');
  late final _llama_kv_cache_clear = _llama_kv_cache_clearPtr
      .asFunction<void Function(ffi.Pointer<llama_context>)>();

  /// Remove tokens from KV cache
  /// seq_id < 0 removes from all sequences
  /// p0 < 0 removes from start
  /// p1 < 0 removes to end
  bool llama_kv_cache_seq_rm(
    ffi.Pointer<llama_context> ctx,
    int seq_id,
    int p0,
    int p1,
  ) {
    return _llama_kv_cache_seq_rm(ctx, seq_id, p0, p1);
  }

  late final _llama_kv_cache_seq_rmPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<llama_context>,
            llama_seq_id,
            llama_pos,
            llama_pos,
          )
        >
      >('llama_kv_cache_seq_rm');
  late final _llama_kv_cache_seq_rm = _llama_kv_cache_seq_rmPtr
      .asFunction<bool Function(ffi.Pointer<llama_context>, int, int, int)>();

  /// Copy tokens from one sequence to another
  void llama_kv_cache_seq_cp(
    ffi.Pointer<llama_context> ctx,
    int seq_id_src,
    int seq_id_dst,
    int p0,
    int p1,
  ) {
    return _llama_kv_cache_seq_cp(ctx, seq_id_src, seq_id_dst, p0, p1);
  }

  late final _llama_kv_cache_seq_cpPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<llama_context>,
            llama_seq_id,
            llama_seq_id,
            llama_pos,
            llama_pos,
          )
        >
      >('llama_kv_cache_seq_cp');
  late final _llama_kv_cache_seq_cp = _llama_kv_cache_seq_cpPtr
      .asFunction<
        void Function(ffi.Pointer<llama_context>, int, int, int, int)
      >();

  /// Shift positions in KV cache
  void llama_kv_cache_seq_add(
    ffi.Pointer<llama_context> ctx,
    int seq_id,
    int p0,
    int p1,
    int delta,
  ) {
    return _llama_kv_cache_seq_add(ctx, seq_id, p0, p1, delta);
  }

  late final _llama_kv_cache_seq_addPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<llama_context>,
            llama_seq_id,
            llama_pos,
            llama_pos,
            llama_pos,
          )
        >
      >('llama_kv_cache_seq_add');
  late final _llama_kv_cache_seq_add = _llama_kv_cache_seq_addPtr
      .asFunction<
        void Function(ffi.Pointer<llama_context>, int, int, int, int)
      >();

  /// Sampler chain
  ffi.Pointer<llama_sampler> llama_sampler_chain_init(
    ffi.Pointer<ffi.Void> params,
  ) {
    return _llama_sampler_chain_init(params);
  }

  late final _llama_sampler_chain_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_sampler> Function(ffi.Pointer<ffi.Void>)
        >
      >('llama_sampler_chain_init');
  late final _llama_sampler_chain_init = _llama_sampler_chain_initPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(ffi.Pointer<ffi.Void>)>();

  void llama_sampler_chain_add(
    ffi.Pointer<llama_sampler> chain,
    ffi.Pointer<llama_sampler> smpl,
  ) {
    return _llama_sampler_chain_add(chain, smpl);
  }

  late final _llama_sampler_chain_addPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<llama_sampler>,
            ffi.Pointer<llama_sampler>,
          )
        >
      >('llama_sampler_chain_add');
  late final _llama_sampler_chain_add = _llama_sampler_chain_addPtr
      .asFunction<
        void Function(ffi.Pointer<llama_sampler>, ffi.Pointer<llama_sampler>)
      >();

  void llama_sampler_free(ffi.Pointer<llama_sampler> smpl) {
    return _llama_sampler_free(smpl);
  }

  late final _llama_sampler_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_sampler>)>
      >('llama_sampler_free');
  late final _llama_sampler_free = _llama_sampler_freePtr
      .asFunction<void Function(ffi.Pointer<llama_sampler>)>();

  void llama_sampler_reset(ffi.Pointer<llama_sampler> smpl) {
    return _llama_sampler_reset(smpl);
  }

  late final _llama_sampler_resetPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_sampler>)>
      >('llama_sampler_reset');
  late final _llama_sampler_reset = _llama_sampler_resetPtr
      .asFunction<void Function(ffi.Pointer<llama_sampler>)>();

  int llama_sampler_sample(
    ffi.Pointer<llama_sampler> smpl,
    ffi.Pointer<llama_context> ctx,
    int idx,
  ) {
    return _llama_sampler_sample(smpl, ctx, idx);
  }

  late final _llama_sampler_samplePtr =
      _lookup<
        ffi.NativeFunction<
          llama_token Function(
            ffi.Pointer<llama_sampler>,
            ffi.Pointer<llama_context>,
            ffi.Int32,
          )
        >
      >('llama_sampler_sample');
  late final _llama_sampler_sample = _llama_sampler_samplePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_sampler>,
          ffi.Pointer<llama_context>,
          int,
        )
      >();

  /// Create samplers
  ffi.Pointer<llama_sampler> llama_sampler_init_greedy() {
    return _llama_sampler_init_greedy();
  }

  late final _llama_sampler_init_greedyPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<llama_sampler> Function()>>(
        'llama_sampler_init_greedy',
      );
  late final _llama_sampler_init_greedy = _llama_sampler_init_greedyPtr
      .asFunction<ffi.Pointer<llama_sampler> Function()>();

  ffi.Pointer<llama_sampler> llama_sampler_init_dist(int seed) {
    return _llama_sampler_init_dist(seed);
  }

  late final _llama_sampler_init_distPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<llama_sampler> Function(ffi.Uint32)>
      >('llama_sampler_init_dist');
  late final _llama_sampler_init_dist = _llama_sampler_init_distPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(int)>();

  ffi.Pointer<llama_sampler> llama_sampler_init_top_k(int k) {
    return _llama_sampler_init_top_k(k);
  }

  late final _llama_sampler_init_top_kPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<llama_sampler> Function(ffi.Int32)>
      >('llama_sampler_init_top_k');
  late final _llama_sampler_init_top_k = _llama_sampler_init_top_kPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(int)>();

  ffi.Pointer<llama_sampler> llama_sampler_init_top_p(double p, int min_keep) {
    return _llama_sampler_init_top_p(p, min_keep);
  }

  late final _llama_sampler_init_top_pPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)
        >
      >('llama_sampler_init_top_p');
  late final _llama_sampler_init_top_p = _llama_sampler_init_top_pPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(double, int)>();

  ffi.Pointer<llama_sampler> llama_sampler_init_min_p(double p, int min_keep) {
    return _llama_sampler_init_min_p(p, min_keep);
  }

  late final _llama_sampler_init_min_pPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)
        >
      >('llama_sampler_init_min_p');
  late final _llama_sampler_init_min_p = _llama_sampler_init_min_pPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(double, int)>();

  ffi.Pointer<llama_sampler> llama_sampler_init_temp(double t) {
    return _llama_sampler_init_temp(t);
  }

  late final _llama_sampler_init_tempPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<llama_sampler> Function(ffi.Float)>
      >('llama_sampler_init_temp');
  late final _llama_sampler_init_temp = _llama_sampler_init_tempPtr
      .asFunction<ffi.Pointer<llama_sampler> Function(double)>();

  ffi.Pointer<llama_sampler> llama_sampler_init_temp_ext(
    double t,
    double delta,
    double exponent,
  ) {
    return _llama_sampler_init_temp_ext(t, delta, exponent);
  }

  late final _llama_sampler_init_temp_extPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Float, ffi.Float)
        >
      >('llama_sampler_init_temp_ext');
  late final _llama_sampler_init_temp_ext = _llama_sampler_init_temp_extPtr
      .asFunction<
        ffi.Pointer<llama_sampler> Function(double, double, double)
      >();

  ffi.Pointer<llama_sampler> llama_sampler_init_penalties(
    int n_vocab,
    int special_eos_id,
    int linefeed_id,
    int penalty_last_n,
    double penalty_repeat,
    double penalty_freq,
    double penalty_present,
    bool penalize_nl,
    bool ignore_eos,
  ) {
    return _llama_sampler_init_penalties(
      n_vocab,
      special_eos_id,
      linefeed_id,
      penalty_last_n,
      penalty_repeat,
      penalty_freq,
      penalty_present,
      penalize_nl,
      ignore_eos,
    );
  }

  late final _llama_sampler_init_penaltiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<llama_sampler> Function(
            ffi.Int32,
            llama_token,
            llama_token,
            ffi.Int32,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Bool,
            ffi.Bool,
          )
        >
      >('llama_sampler_init_penalties');
  late final _llama_sampler_init_penalties = _llama_sampler_init_penaltiesPtr
      .asFunction<
        ffi.Pointer<llama_sampler> Function(
          int,
          int,
          int,
          int,
          double,
          double,
          double,
          bool,
          bool,
        )
      >();

  /// Performance timing info
  void llama_perf_context_print(ffi.Pointer<llama_context> ctx) {
    return _llama_perf_context_print(ctx);
  }

  late final _llama_perf_context_printPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_context>)>
      >('llama_perf_context_print');
  late final _llama_perf_context_print = _llama_perf_context_printPtr
      .asFunction<void Function(ffi.Pointer<llama_context>)>();

  void llama_perf_context_reset(ffi.Pointer<llama_context> ctx) {
    return _llama_perf_context_reset(ctx);
  }

  late final _llama_perf_context_resetPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_context>)>
      >('llama_perf_context_reset');
  late final _llama_perf_context_reset = _llama_perf_context_resetPtr
      .asFunction<void Function(ffi.Pointer<llama_context>)>();

  /// Print system info
  ffi.Pointer<ffi.Char> llama_print_system_info() {
    return _llama_print_system_info();
  }

  late final _llama_print_system_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'llama_print_system_info',
      );
  late final _llama_print_system_info = _llama_print_system_infoPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Set log callback
  void llama_log_set(
    ffi.Pointer<ffi.Void> log_callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _llama_log_set(log_callback, user_data);
  }

  late final _llama_log_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
        >
      >('llama_log_set');
  late final _llama_log_set = _llama_log_setPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
      >();

  /// Get number of physical CPU cores
  int llama_max_devices() {
    return _llama_max_devices();
  }

  late final _llama_max_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('llama_max_devices');
  late final _llama_max_devices = _llama_max_devicesPtr
      .asFunction<int Function()>();
}

/// Forward declarations
final class llama_model extends ffi.Opaque {}

final class llama_context extends ffi.Opaque {}

final class llama_sampler extends ffi.Opaque {}

typedef llama_pos = ffi.Int32;
typedef Dartllama_pos = int;
typedef llama_token = ffi.Int32;
typedef Dartllama_token = int;
typedef llama_seq_id = ffi.Int32;
typedef Dartllama_seq_id = int;

/// Model vocabulary type
enum llama_vocab_type {
  /// For models without a vocabulary
  LLAMA_VOCAB_TYPE_NONE(0),

  /// SentencePiece
  LLAMA_VOCAB_TYPE_SPM(1),

  /// Byte Pair Encoding
  LLAMA_VOCAB_TYPE_BPE(2),

  /// WordPiece
  LLAMA_VOCAB_TYPE_WPM(3),

  /// Unigram
  LLAMA_VOCAB_TYPE_UGM(4),

  /// RWKV
  LLAMA_VOCAB_TYPE_RWKV(5);

  final int value;
  const llama_vocab_type(this.value);

  static llama_vocab_type fromValue(int value) => switch (value) {
    0 => LLAMA_VOCAB_TYPE_NONE,
    1 => LLAMA_VOCAB_TYPE_SPM,
    2 => LLAMA_VOCAB_TYPE_BPE,
    3 => LLAMA_VOCAB_TYPE_WPM,
    4 => LLAMA_VOCAB_TYPE_UGM,
    5 => LLAMA_VOCAB_TYPE_RWKV,
    _ => throw ArgumentError('Unknown value for llama_vocab_type: $value'),
  };
}

/// Token types
enum llama_token_type {
  LLAMA_TOKEN_TYPE_UNDEFINED(0),
  LLAMA_TOKEN_TYPE_NORMAL(1),
  LLAMA_TOKEN_TYPE_UNKNOWN(2),
  LLAMA_TOKEN_TYPE_CONTROL(3),
  LLAMA_TOKEN_TYPE_USER_DEFINED(4),
  LLAMA_TOKEN_TYPE_UNUSED(5),
  LLAMA_TOKEN_TYPE_BYTE(6);

  final int value;
  const llama_token_type(this.value);

  static llama_token_type fromValue(int value) => switch (value) {
    0 => LLAMA_TOKEN_TYPE_UNDEFINED,
    1 => LLAMA_TOKEN_TYPE_NORMAL,
    2 => LLAMA_TOKEN_TYPE_UNKNOWN,
    3 => LLAMA_TOKEN_TYPE_CONTROL,
    4 => LLAMA_TOKEN_TYPE_USER_DEFINED,
    5 => LLAMA_TOKEN_TYPE_UNUSED,
    6 => LLAMA_TOKEN_TYPE_BYTE,
    _ => throw ArgumentError('Unknown value for llama_token_type: $value'),
  };
}

/// Model file types
enum llama_ftype {
  LLAMA_FTYPE_ALL_F32(0),
  LLAMA_FTYPE_MOSTLY_F16(1),
  LLAMA_FTYPE_MOSTLY_Q4_0(2),
  LLAMA_FTYPE_MOSTLY_Q4_1(3),
  LLAMA_FTYPE_MOSTLY_Q8_0(7);

  final int value;
  const llama_ftype(this.value);

  static llama_ftype fromValue(int value) => switch (value) {
    0 => LLAMA_FTYPE_ALL_F32,
    1 => LLAMA_FTYPE_MOSTLY_F16,
    2 => LLAMA_FTYPE_MOSTLY_Q4_0,
    3 => LLAMA_FTYPE_MOSTLY_Q4_1,
    7 => LLAMA_FTYPE_MOSTLY_Q8_0,
    _ => throw ArgumentError('Unknown value for llama_ftype: $value'),
  };
}

/// Split mode
enum llama_split_mode {
  /// single GPU
  LLAMA_SPLIT_MODE_NONE(0),

  /// split layers across GPUs
  LLAMA_SPLIT_MODE_LAYER(1),

  /// split rows across GPUs
  LLAMA_SPLIT_MODE_ROW(2);

  final int value;
  const llama_split_mode(this.value);

  static llama_split_mode fromValue(int value) => switch (value) {
    0 => LLAMA_SPLIT_MODE_NONE,
    1 => LLAMA_SPLIT_MODE_LAYER,
    2 => LLAMA_SPLIT_MODE_ROW,
    _ => throw ArgumentError('Unknown value for llama_split_mode: $value'),
  };
}

/// RoPE scaling type
enum llama_rope_scaling_type {
  LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED(-1),
  LLAMA_ROPE_SCALING_TYPE_NONE(0),
  LLAMA_ROPE_SCALING_TYPE_LINEAR(1),
  LLAMA_ROPE_SCALING_TYPE_YARN(2);

  static const LLAMA_ROPE_SCALING_TYPE_MAX_VALUE = LLAMA_ROPE_SCALING_TYPE_YARN;

  final int value;
  const llama_rope_scaling_type(this.value);

  static llama_rope_scaling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED,
    0 => LLAMA_ROPE_SCALING_TYPE_NONE,
    1 => LLAMA_ROPE_SCALING_TYPE_LINEAR,
    2 => LLAMA_ROPE_SCALING_TYPE_YARN,
    _ => throw ArgumentError(
      'Unknown value for llama_rope_scaling_type: $value',
    ),
  };

  @override
  String toString() {
    if (this == LLAMA_ROPE_SCALING_TYPE_YARN)
      return "llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_YARN, llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_MAX_VALUE";
    return super.toString();
  }
}

/// Pooling type
enum llama_pooling_type {
  LLAMA_POOLING_TYPE_UNSPECIFIED(-1),
  LLAMA_POOLING_TYPE_NONE(0),
  LLAMA_POOLING_TYPE_MEAN(1),
  LLAMA_POOLING_TYPE_CLS(2),
  LLAMA_POOLING_TYPE_LAST(3);

  final int value;
  const llama_pooling_type(this.value);

  static llama_pooling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_POOLING_TYPE_UNSPECIFIED,
    0 => LLAMA_POOLING_TYPE_NONE,
    1 => LLAMA_POOLING_TYPE_MEAN,
    2 => LLAMA_POOLING_TYPE_CLS,
    3 => LLAMA_POOLING_TYPE_LAST,
    _ => throw ArgumentError('Unknown value for llama_pooling_type: $value'),
  };
}

/// Attention type
enum llama_attention_type {
  LLAMA_ATTENTION_TYPE_UNSPECIFIED(-1),
  LLAMA_ATTENTION_TYPE_CAUSAL(0),
  LLAMA_ATTENTION_TYPE_NON_CAUSAL(1);

  final int value;
  const llama_attention_type(this.value);

  static llama_attention_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ATTENTION_TYPE_UNSPECIFIED,
    0 => LLAMA_ATTENTION_TYPE_CAUSAL,
    1 => LLAMA_ATTENTION_TYPE_NON_CAUSAL,
    _ => throw ArgumentError('Unknown value for llama_attention_type: $value'),
  };
}

/// Model parameters
final class llama_model_params extends ffi.Struct {
  /// number of layers to store in VRAM
  @ffi.Int32()
  external int n_gpu_layers;

  /// how to split the model across GPUs
  @ffi.UnsignedInt()
  external int split_modeAsInt;

  llama_split_mode get split_mode =>
      llama_split_mode.fromValue(split_modeAsInt);

  /// main GPU to use
  @ffi.Int32()
  external int main_gpu;

  /// how to split layers across GPUs (size: 128)
  external ffi.Pointer<ffi.Float> tensor_split;

  /// Progress callback
  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  /// Override key-value pairs
  external ffi.Pointer<ffi.Void> kv_overrides;

  /// Model vocabulary type override
  @ffi.Bool()
  external bool vocab_only;

  @ffi.Bool()
  external bool use_mmap;

  @ffi.Bool()
  external bool use_mlock;

  @ffi.Bool()
  external bool check_tensors;
}

/// Context parameters
final class llama_context_params extends ffi.Struct {
  /// text context, 0 = from model
  @ffi.Uint32()
  external int n_ctx;

  /// logical maximum batch size
  @ffi.Uint32()
  external int n_batch;

  /// physical maximum batch size
  @ffi.Uint32()
  external int n_ubatch;

  /// max number of sequences
  @ffi.Uint32()
  external int n_seq_max;

  /// number of threads for generation
  @ffi.Int32()
  external int n_threads;

  /// number of threads for batch processing
  @ffi.Int32()
  external int n_threads_batch;

  @ffi.Int()
  external int rope_scaling_typeAsInt;

  llama_rope_scaling_type get rope_scaling_type =>
      llama_rope_scaling_type.fromValue(rope_scaling_typeAsInt);

  @ffi.Int()
  external int pooling_typeAsInt;

  llama_pooling_type get pooling_type =>
      llama_pooling_type.fromValue(pooling_typeAsInt);

  @ffi.Int()
  external int attention_typeAsInt;

  llama_attention_type get attention_type =>
      llama_attention_type.fromValue(attention_typeAsInt);

  @ffi.Float()
  external double rope_freq_base;

  @ffi.Float()
  external double rope_freq_scale;

  @ffi.Float()
  external double yarn_ext_factor;

  @ffi.Float()
  external double yarn_attn_factor;

  @ffi.Float()
  external double yarn_beta_fast;

  @ffi.Float()
  external double yarn_beta_slow;

  @ffi.Uint32()
  external int yarn_orig_ctx;

  @ffi.Float()
  external double defrag_thold;

  /// Abort callback
  external ffi.Pointer<ffi.Void> abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_data;

  /// Type of quantization
  @ffi.Int()
  external int type_k;

  @ffi.Int()
  external int type_v;

  @ffi.Bool()
  external bool logits_all;

  @ffi.Bool()
  external bool embeddings;

  @ffi.Bool()
  external bool offload_kqv;

  @ffi.Bool()
  external bool flash_attn;

  @ffi.Bool()
  external bool no_perf;
}

/// Model quantization parameters
final class llama_model_quantize_params extends ffi.Struct {
  @ffi.Int32()
  external int nthread;

  @ffi.UnsignedInt()
  external int ftypeAsInt;

  llama_ftype get ftype => llama_ftype.fromValue(ftypeAsInt);

  @ffi.Int32()
  external int output_tensor_type;

  @ffi.Int32()
  external int token_embedding_type;

  @ffi.Bool()
  external bool allow_requantize;

  @ffi.Bool()
  external bool quantize_output_tensor;

  @ffi.Bool()
  external bool only_copy;

  @ffi.Bool()
  external bool pure;

  @ffi.Bool()
  external bool keep_split;

  external ffi.Pointer<ffi.Void> imatrix;

  external ffi.Pointer<ffi.Void> kv_overrides;
}

/// Batch for submitting tokens
final class llama_batch extends ffi.Struct {
  @ffi.Int32()
  external int n_tokens;

  external ffi.Pointer<llama_token> token;

  external ffi.Pointer<ffi.Float> embd;

  external ffi.Pointer<llama_pos> pos;

  external ffi.Pointer<ffi.Int32> n_seq_id;

  external ffi.Pointer<ffi.Pointer<llama_seq_id>> seq_id;

  external ffi.Pointer<ffi.Int8> logits;
}

/// Token data
final class llama_token_data extends ffi.Struct {
  @llama_token()
  external int id;

  @ffi.Float()
  external double logit;

  @ffi.Float()
  external double p;
}

/// Token data array
final class llama_token_data_array extends ffi.Struct {
  external ffi.Pointer<llama_token_data> data;

  @ffi.Size()
  external int size;

  @ffi.Int64()
  external int selected;

  @ffi.Bool()
  external bool sorted;
}
